openapi: 3.0.0
paths:
  "/user":
    get:
      operationId: UsersController_getUsers
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - User
    post:
      operationId: UsersController_createUser
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateUserDTO"
      responses:
        '201':
          description: ''
      tags:
        - User
  "/user/{id}":
    get:
      operationId: UsersController_getUserById
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - User
    put:
      operationId: UsersController_updateUser
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateUserDTO"
      responses:
        '200':
          description: ''
      tags:
        - User
    delete:
      operationId: UsersController_deleteUser
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - User
  "/artist":
    get:
      operationId: ArtistsController_getAllArtists
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Artist
    post:
      operationId: ArtistsController_createArtist
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateArtistDTO"
      responses:
        '201':
          description: ''
      tags:
        - Artist
  "/artist/{id}":
    get:
      operationId: ArtistsController_getArtistById
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Artist
    put:
      operationId: ArtistsController_updateArtist
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateArtistDTO"
      responses:
        '200':
          description: ''
      tags:
        - Artist
    delete:
      operationId: ArtistsController_deleteArtist
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - Artist
  "/album":
    get:
      operationId: AlbumsController_getAllAlbums
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Album
    post:
      operationId: AlbumsController_createAlbum
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateAlbumDTO"
      responses:
        '201':
          description: ''
      tags:
        - Album
  "/album/{id}":
    get:
      operationId: AlbumsController_getAlbumById
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Album
    put:
      operationId: AlbumsController_updateAlbum
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateAlbumDTO"
      responses:
        '200':
          description: ''
      tags:
        - Album
    delete:
      operationId: AlbumsController_deleteAlbum
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - Album
  "/track":
    get:
      operationId: TracksController_getAllTracks
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Track
    post:
      operationId: TracksController_createTrack
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateTrackDTO"
      responses:
        '201':
          description: ''
      tags:
        - Track
  "/track/{id}":
    get:
      operationId: TracksController_getTrackById
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Track
    put:
      operationId: TracksController_updateTrack
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateTrackDTO"
      responses:
        '200':
          description: ''
      tags:
        - Track
    delete:
      operationId: TracksController_deleteTrack
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - Track
  "/favs":
    get:
      operationId: FavoritesController_getAllFavoriteItems
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Favorite
  "/favs/track/{id}":
    post:
      operationId: FavoritesController_addFavoriteTrack
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '201':
          description: ''
      tags:
        - Favorite
    delete:
      operationId: FavoritesController_deleteTrackFromFavorites
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - Favorite
  "/favs/album/{id}":
    post:
      operationId: FavoritesController_addFavoriteAlbum
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '201':
          description: ''
      tags:
        - Favorite
    delete:
      operationId: FavoritesController_deleteAlbumFromFavorites
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - Favorite
  "/favs/artist/{id}":
    post:
      operationId: FavoritesController_addFavoriteArtist
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '201':
          description: ''
      tags:
        - Favorite
    delete:
      operationId: FavoritesController_deleteArtistFromFavorites
      parameters:
        - name: id
          required: true
          in: path
          example: adb19b97-a92a-41aa-ad81-e872317386a4
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - Favorite
info:
  title: Home Library Service
  description: Home library service task
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    CreateUserDTO:
      type: object
      properties:
        login:
          type: string
          example: Kobe_Schowalter92
        password:
          type: string
          example: liodGB3buGGIz9E
      required:
        - login
        - password
    UpdateUserDTO:
      type: object
      properties:
        oldPassword:
          type: string
          example: liodGB3buGGIz9E
        newPassword:
          type: string
          example: 522eHeSAfHRQnVO
      required:
        - oldPassword
        - newPassword
    CreateArtistDTO:
      type: object
      properties:
        name:
          type: string
          example: Jeannie Runte Jr.
        grammy:
          type: boolean
          example: true
      required:
        - name
        - grammy
    UpdateArtistDTO:
      type: object
      properties:
        name:
          type: string
          example: Jeannie Runte Jr.
        grammy:
          type: boolean
          example: true
      required:
        - name
        - grammy
    CreateAlbumDTO:
      type: object
      properties:
        name:
          type: string
          example: Makin' Whoopee
        year:
          type: number
          example: 1997
        artistId:
          type: string
          example: 30f38050-6cab-4cd2-838f-68f1fd981896
      required:
        - name
        - year
    UpdateAlbumDTO:
      type: object
      properties:
        name:
          type: string
          example: Makin' Whoopee
        year:
          type: number
          example: 1997
        artistId:
          type: string
          example: 30f38050-6cab-4cd2-838f-68f1fd981896
      required:
        - name
        - year
    CreateTrackDTO:
      type: object
      properties:
        name:
          type: string
          example: Lean On Me
        artistId:
          type: string
          example: 0c4f1f3b-3629-4df8-9fe7-eda73cd9158e
        albumId:
          type: string
          example: 42294885-ea87-4703-87dc-b3fdc91eddcf
        duration:
          type: number
          example: 71254
      required:
        - name
        - duration
    UpdateTrackDTO:
      type: object
      properties:
        name:
          type: string
          example: Lean On Me
        artistId:
          type: string
          example: 0c4f1f3b-3629-4df8-9fe7-eda73cd9158e
        albumId:
          type: string
          example: 42294885-ea87-4703-87dc-b3fdc91eddcf
        duration:
          type: number
          example: 71254
      required:
        - name
        - duration
